---
title: "03-Time-series-decomposition"
author: "Elad Danovich"
date: "2024-05-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Time series decomposition

```{r}
library(fpp3)
```

## Transformations and adjustments
```{r}
global_economy |>
  filter(Country == "Australia") |>
  autoplot(GDP / Population)
```
```{r}
food <- aus_retail |>
  filter(Industry == "Food retailing") |>
  summarise(Turnover = sum(Turnover))
food |> autoplot(Turnover)
```
```{r}
food |> autoplot(sqrt(Turnover)) + 
  labs(y = "square root turnover")
```
```{r}
food |> autoplot((Turnover)^1/3) + 
  labs(y = "cube root turnover")
```
```{r}
food |> autoplot(log(Turnover)) + 
  labs(y = "log  turnover")
```
```{r}
food |>
  features(Turnover, features = guerrero)
```



## Time series components
y_t = f(S_t, T_t, R_t) / add or multiply
```{r}
us_retail_emp <- us_employment |>
  filter(year(Month) >= 1990, Title == "Retail Trade") |>
  select(-Series_ID)
us_retail_emp
```
```{r}
us_retail_emp |>
  autoplot(Employed) +
  labs(y = "Persons (thousands)", title = "Total employment in US retail")
```
```{r}
dcmp <- us_retail_emp |>
  model(stl = STL(Employed))
components(dcmp)
```
y_t = T_t + S_t + R_t
```{r}
components(dcmp) |> autoplot()
```
```{r}
us_retail_emp |>
  autoplot(Employed, color="gray") +
  autolayer(components(dcmp), trend, color = "#D55E00") +
  labs(y = "Persons (thousands)", title = "Total employment in US retail")
```
```{r}
components(dcmp) |> gg_subseries(season_year)
```
```{r}
us_retail_emp |>
  autoplot(Employed, color="gray") +
  autolayer(components(dcmp), season_adjust, color = "#D55E00") +
  labs(y = "Persons (thousands)", title = "Total employment in US retail")
```
 
 
 
## Moving averages













## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
